#include "protheus.ch"

User Function SE5Hist()
	_cRet := IF(FUNNAME()$"FINA040,FINA740,FINA200","REC REF " + ALLTRIM(SE1->E1_PREFIXO) + " " + ALLTRIM(SE1->E1_NUM) + ALLTRIM(SE1->E1_PARCELA) + " " + ALLTRIM(SE1->E1_NOMCLI),IF(FUNNAME()$"FINA080,FINA750,FINA430","PAG REF "  + ALLTRIM(SE2->E2_PREFIXO) + " " + ALLTRIM(SE2->E2_NUM) + ALLTRIM(SE2->E2_PARCELA) + " " + ALLTRIM(SE2->E2_NOMFOR) ,""))
Return (_cRet)